### ISSUE TITLE
Can't login using Gmail Authentication

### ISSUE THREAD

**Issue by harleyds** [0sm0s1z/Voltaire#11]
Hello, I'm trying to login and have selected my gmail account, but it doesn't authenticate and allow me access. After I select the Login button, it prompts me to select my Gmail account. I select my account, the page reloads and brings me back to the previous page which shows the Login and Export Button. The button shown in the video, Create New Index does not appear. If I select Login again, it goes back to the page to select a gmail account.

Hope this helps for a resolution.

Thanks.

**Comment by 0sm0s1z** [comment]
Thanks for posting! I've actually seen this issue before, unfortunately it's an issue with Google's authentication engine. Using a different browser or system sometimes fixes the issue. Alternately, it does seem to go away eventually. It's really hard to diagnose what the trouble is on the Google side. I hope that helps, let us know if you find a more direct fix!
