### ISSUE TITLE
All items are lost if you import CSV

### ISSUE THREAD

**Issue by walhajri** [0sm0s1z/Voltaire#14]
I lost my index after I tried to use the "Import CSV" It overwrites it.

Luckily I already exported the index 
 
![voltaire](https://user-images.githubusercontent.com/25450916/70965421-b3b41080-20a0-11ea-80b1-550de8f210a6.png)
![voltaire1](https://user-images.githubusercontent.com/25450916/70965437-b878c480-20a0-11ea-88be-de7f571a7358.png)

**Comment by 0sm0s1z** [comment]
That is correct when you upload an index it becomes that index. This is by intent, but I realize that it's super confusing and even a bit dangerous. There's a big update to Voltaire that's launching January 1st that has a lot of checks and balances for these kinds of things!
