### ISSUE TITLE
Requirements for local install

### ISSUE THREAD

**Issue by garanews** [0sm0s1z/Voltaire#18]
I'm running
node --version
v12.16.3
firebase --version
3.16.0
npm --version
6.14.4

trying to do firebase serve but getting:
**Error: Server Error. certificate has expired**
looking here https://github.com/firebase/firebase-tools/issues/1901 
It seems need to update versions because old version are pointing to
https://admin.firebase.com/ that has cert expired on Jan 2020
With latest firebase it should point to *.firebase.google.com where cert is ok.

**Comment by 0sm0s1z** [comment]
Are you sure you want to build it locally? It'll take a good bit of doing as you'll need to create a firebase account and set up a cloud data store. Are you trying to dev?

**Comment by garanews** [comment]
Yes I have account, able to authenticate with external page but then giving that error
