### ISSUE TITLE
Generated Index no Z words

### ISSUE THREAD

**Issue by dustingit** [0sm0s1z/Voltaire#20]
I've noticed that any word starting with a Z does not show up in my generated index. I did have few letters that didn't have entries, so I created blank entries for them hoping that would fix the issue, it didn't.

The import was of a XLSX spreadsheet and I tested with an xls version. 
I tried manually adding an entry with a Z in Voltaire but that didn't seem to work either.

Thanks in advance and thanks for the tool.
[No Z.docx](https://github.com/0sm0s1z/Voltaire/files/4759942/No.Z.docx)

**Comment by 5A4B48** [comment]
I'm having this same issue as well.

**Comment by viprsec** [comment]
I too am having this issue, it also does not print entries that start with a non-alpha character.

Temp workaround suggested by @0sm0s1z in email was to append "y" to the front of my Z and non-alpha entries and correct them post export. Testing shows that has been an acceptable workaround.  Posting for others so they don't bother the author too much.
