### ISSUE TITLE
When I export it does not export anything that starts with  non letters. 

### ISSUE THREAD

**Issue by Jonesckevin** [0sm0s1z/Voltaire#21]
When exporting the Index it will always export in docx format for me as well as ignore non alpha starting characters.

Example:
$MFT
$VOLUME_NAME
.\
\Device\PhysicalMemory

**Comment by viprsec** [comment]
This is a known issue I raised to the developer. The work around that worked for me was to toss "qq" in front of the items. Then after the export manually move them into the correct section in your office editor of choice.
