### ISSUE TITLE
Authentication broken - cannot log in or access on Chrome or Firefox

### ISSUE THREAD

**Issue by omnicode0** [0sm0s1z/Voltaire#40]
Attempting to authenticate with Google on Chrome and Firefox returns me to the home page without any access to the application. Would like to use this to study for SANS test I am taking in 2 weeks.

![Voltaire_Auth_Issue_Loop_1](https://user-images.githubusercontent.com/63731332/170558141-36e22d20-1e92-4eb6-823b-27f68513d412.PNG)
![Voltaire_Auth_Issue_Loop_2](https://user-images.githubusercontent.com/63731332/170558159-baaec7ba-91d8-4477-91e9-c2a78fac74a0.PNG)
![Voltaire_Auth_Issue_Loop_3](https://user-images.githubusercontent.com/63731332/170558172-31654672-2098-48cc-89a2-0a23a1725e08.PNG)

**Comment by 0sm0s1z** [comment]
It's your computer / browsers. It's cashed something related to Google auth that I can't fix. The issue will resolve on its own eventually when your local cache times out (you might be able to purge this manually, but I can't help with that).

The easiest solution is to use another computer. If you don't have one try it in a VM.
