### ISSUE TITLE
Can't open page because address is invalid...

### ISSUE THREAD

**Issue by IPv4est** [0sm0s1z/Voltaire#52]
Please help. I was nearly finished my index.

**Comment by amitrana3** [comment]
same issue I have this morning. works good last night

**Comment by MostafaSoliman** [comment]
same here, Please don't tell me i have to redo my index again

**Comment by 0sm0s1z** [comment]
Please head to the discord support channel if you'd like live updates on this issue. We're currently waiting for Google domains to address the support ticket I have with them.

**Comment by Scoobysnax1234** [comment]
what is the link to the discord?

**Comment by 0sm0s1z** [comment]
https://discord.gg/opensecurity

**Comment by Scoobysnax1234** [comment]
Thanks!

**Comment by 0sm0s1z** [comment]
Outage solved. Thanks for the report all!
