### ISSUE TITLE
Error when trying to open index

### ISSUE THREAD

**Issue by ab600** [0sm0s1z/Voltaire#53]
I keep getting this error when trying to open my DOC formatted index. If I select PDF, the file does not download at all.

![Screenshot 2024-05-07 175316](https://github.com/0sm0s1z/Voltaire/assets/141168433/35127d72-49c1-44bc-ada5-366bdf96c4c6)

**Comment by 0sm0s1z** [comment]
Use the project discord to keep tabs on known bugs and product feature improvements.
