### ISSUE TITLE
Invalid Syntax

### ISSUE THREAD

**Issue by TheRabbitHoleLabs** [0sm0s1z/Voltaire#6]
Hello, I keep getting an error that the file has invalid systax when I try to run the file xenocrates.py in the Python IDLE.  Any help would be greatly appreciated.

**Comment by 0sm0s1z** [comment]
I'm actually pushing a very large update over the weekend that's hound fix most major troubles with the program, hope that's alright? If you're looking to get it done in the short term it's likely a format issue with your spreadsheet, make sure it's saved as a tab delimited document. (That won't be a requirement in the upcoming version).

**Comment by TheRabbitHoleLabs** [comment]
That would be great! My file is saved as a Tab Delimited doxument. But I
can't even get the .py file to run in the IDLE. I installed Python corectly
and set my extensions but the file won't open without the error.

I really appreciate so much work you are putting into such a great idea!!
