### ISSUE TITLE
Build Index Orders Items Incorrectly

### ISSUE THREAD

**Issue by 0sm0s1z** [0sm0s1z/Voltaire#9]
There is an issue with Voltaire where not all indexed words are under the correct headings. At the moment all letters must be represented as "Title" somewhere.

A fix for this issue is incoming. An interim solution is to create an entry for every letter ie "A,B,C..."

**Comment by BamaCoder** [comment]
This issue should be fixed in my most recent fork commit. Let me know if this fixes the issue as I do not have time to recreate and configure the project for Firebase. See [here](https://github.com/0sm0s1z/Voltaire/compare/master...BamaCoder:master)

**Comment by BamaCoder** [comment]
Could this code here be used in place of your existing for loop in ExportIndex.js? It should fix the issue provided there are no bugs. The only problem that I can see is that it will output a page break on the first execution but that can be fixed easily. Sadly can't test because I have had a ton of trouble trying to replicate the configure and set up the project locally (probably because Windows).

    var curChar = "";
    var curHeader = "";
	for (let item in tmpList) {
        var curTitle = tmpList[item].title.value.trim();
        if (typeof curTitle == 'string') {
           curChar = curTitle.at(0).toLowerCase();
           if(!(curChar.match(/[a-z]/i))  curChar = "#"; // Sets header to '#' if character is not a through z
           if (curChar !== curHeader) {
              curHeader = curChar;
              tmpList2.push({
		     title: {__html: "{{pagebreak}}<center><span class='dex-heading'>" + curHeader + curHeader.toUpperCase() + "</span></center>"},
	             description: "",
		     page: "",
		     book: ""
		  });
           }
              tmpList2.push({
                 title: {__html: tmpList[item].title.value},
                 description: tmpList[item].description.value,
                 page: "[b" + tmpList[item].book.value + "/p" + tmpList[item].page.value +"]",
                 book: tmpList[item].book.value
              });
        }       
    }

**Comment by walhajri** [comment]
Yes, it works!! 

Thank you
